data:
  train: en-fi-fr-sv
model:
  name: facebook/xlm-roberta-xl
  low_cpu_mem_usage: True
trainer:
  learning_rate: 1e-4
  gradient_accumulation_steps: 4
peft:
  enable: True
dataloader:
  train_batch_size: 4
  balancing_sampler: True
