data:
  train: en-fi-fr-sv-tr
  max_length: 2048
model:
  name: BAAI/bge-m3-retromae
trainer:
  learning_rate: 3e-5
  gradient_accumulation_steps: 4
dataloader:
  balancing_sampler: True
  train_batch_size: 2
  dev_batch_size: 64
  test_batch_size: 64
