data:
  train: en-fi-fr-sv-tr
model:
  name: google/mt5-large
trainer:
  learning_rate: 5e-5
  gradient_accumulation_steps: 2
peft:
  enable: True
dataloader:
  train_batch_size: 4
  balancing_sampler: True
