data:
  train: en-fi-fr-sv-tr
  max_length: 2048
  output_suffix: "full"
model:
  name: BAAI/bge-m3
trainer:
  learning_rate: 3e-5
  gradient_accumulation_steps: 8
dataloader:
  balancing_sampler: True
  train_batch_size: 1
  dev_batch_size: 16
  test_batch_size: 16
