data:
  train: en-fi-fr-sv
model:
  name: mistralai/Mixtral-8x7B-v0.1
  low_cpu_mem_usage: True
trainer:
  learning_rate: 1e-4
  gradient_accumulation_steps: 4
peft:
  enable: True
dataloader:
  train_batch_size: 3
  dev_batch_size: 4
  test_batch_size: 4
  balancing_sampler: True
