data:
  train: ar-ca-en-es-fa-fi-fr-hi-id-jp-no-pt-sv-tr-ur-zh
  dev: en-fi-fr-sv
  test: en-fi-fr-sv
  no_dynamic_padding: True
  remove_unused_cols: False
model:
  name: xlm-roberta-large
dataloader:
  balancing_sampler: False
torch_dtype: float32
