data:
  train: en-fi-fr-sv-tr
  max_length: 512
  output_suffix: "512"
model:
  name: BAAI/bge-m3
trainer:
  learning_rate: 6e-5
  gradient_accumulation_steps: 2
dataloader:
  balancing_sampler: True
  train_batch_size: 8
  dev_batch_size: 16
  test_batch_size: 16
