data:
  train: en-fi-fr-sv-tr
model:
  name: google/umt5-xl
trainer:
  learning_rate: 3e-4
  gradient_accumulation_steps: 4
peft:
  enable: True
dataloader:
  train_batch_size: 2
  dev_batch_size: 8
  test_batch_size: 8
  balancing_sampler: True
