data:
  train: en-fi-fr-sv-tr
model:
  name: google/umt5-xl
trainer:
  learning_rate: 5e-5
  gradient_accumulation_steps: 8
dataloader:
  train_batch_size: 1
  dev_batch_size: 8
  test_batch_size: 8
  balancing_sampler: True
