wandb_version: 1

seed:
  desc: null
  value: 42
method:
  desc: null
  value: finetune
torch_dtype:
  desc: null
  value: torch.bfloat16
device:
  desc: null
  value: cuda
data:
  desc: null
  value: Namespace(train='sv', dev=None, test=None, labels='all', output_path='output',
    source_path='data', max_length=512, return_tensors='pt')
model:
  desc: null
  value: Namespace(name='xlm-roberta-base', compile=False, save=False)
trainer:
  desc: null
  value: Namespace(epochs=30, learning_rate=0.0001, weight_decay=0.05, warmup_ratio=0.01,
    loss_alpha=0.75, loss_gamma=2, patience=5, best_model_metric='dev/f1')
dataloader:
  desc: null
  value: Namespace(train_batch_size=8, dev_batch_size=8, test_batch_size=8, balancing_sampler=False)
config:
  desc: null
  value:
  - v3/configs/labels_all/xlmr-base/sv.yaml
label_scheme:
  desc: null
  value:
  - HI
  - ID
  - IN
  - IP
  - LY
  - MT
  - NA
  - OP
  - SP
  - av
  - ds
  - dtp
  - ed
  - en
  - fi
  - it
  - lt
  - nb
  - ne
  - ob
  - ra
  - re
  - rs
  - rv
  - sr
num_labels:
  desc: null
  value: 25
working_dir:
  desc: null
  value: output/labels_all/xlm-roberta-base/sv__
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705489530.086796
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.2
      6: 4.35.0
      8:
      - 4
      - 5
      13: darwin-arm64
