train: en-fi-fr-sv-tr
test: en-fi-fr-sv-tr-ar-ca-es-fa-hi-id-jp-no-pt-ur-zh
model_name: facebook/xlm-roberta-xl
learning_rate: 1e-4
train_batch_size: 2
grad_acc_steps: 4
peft: True
lora_rank: 64
lora_alpha: 64
