train_using_embeddings: 1024
torch_dtype: float
data:
  train: fr
  no_dynamic_padding: True
  text_prefix: "query: "
model:
  name: smart-tribune/sentence-transformers-multilingual-e5-large
trainer:
  learning_rate: 5e-5
