data:
  train: en-fi-fr-sv
model:
  name: google/madlad400-3b-mt
trainer:
  learning_rate: 1e-4
  gradient_accumulation_steps: 4
peft:
  enable: True
dataloader:
  train_batch_size: 3
  dev_batch_size: 4
  test_batch_size: 4
