method: predict
timer: True
save_predictions: False
data:
  train: en-fi-fr-sv-tr
  use_inference_time_test_data: True
  max_length: 2048
model:
  name: BAAI/bge-m3-retromae
dataloader:
  balancing_sampler: True
  test_batch_size: 1
