method: predict
timer: True
save_predictions: False
data:
  train: en-fi-fr-sv-tr
  labels: upper
  use_inference_time_test_data: True
model:
  name: xlm-roberta-large
dataloader:
  balancing_sampler: True
  test_batch_size: 1
# 18.166394
