data:
  train: sv
model:
  name: google/madlad400-3b-mt
trainer:
  learning_rate: 1e-4
  gradient_accumulation_steps: 8
peft:
  enable: True
dataloader:
  train_batch_size: 1
  dev_batch_size: 8
  test_batch_size: 8
