data:
  train: sv
model:
  name: google/madlad400-3b-mt
trainer:
  learning_rate: 1e-4
  gradient_accumulation_steps: 2
peft:
  enable: True
dataloader:
  train_batch_size: 4
  dev_batch_size: 32
  test_batch_size: 32
